version: '3.8'
services:
  aplicacion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electronica-vallarta-app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__ConexionSqlServer: ${CADENA_CONEXION_SQLSERVER}
    ports:
      - "8080:8080"
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
volumes:
  dataprotection_keys: