// <auto-generated />
using System;
using ElectronicaVallarta.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicaVallarta.Migrations
{
    [DbContext(typeof(ContextoAplicacion))]
    [Migration("20260406172347_AgregarRegistroConsultaAnalitica")]
    partial class AgregarRegistroConsultaAnalitica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SimboloMoneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.RegistroConsultaAnalitica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionRango")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EsExitosa")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaConsultaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificadorSesionAnonima")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdiomaNavegador")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpCliente")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("MetodoHttp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("MontoConsultadoUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombrePais")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreRegion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreSucursal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RangoMontoDesdeUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RangoMontoHastaUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referer")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RegionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ResultadoObtenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RutaOrigen")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TasaCambioAplicada")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("TasaCambioRangoId")
                        .HasColumnType("int");

                    b.Property<long>("TiempoRespuestaMs")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("DescripcionRango");

                    b.HasIndex("FechaConsultaUtc");

                    b.HasIndex("IdentificadorSesionAnonima");

                    b.HasIndex("FechaConsultaUtc", "EsExitosa");

                    b.HasIndex("PaisId", "FechaConsultaUtc");

                    b.HasIndex("SucursalId", "FechaConsultaUtc");

                    b.HasIndex("TasaCambioRangoId", "FechaConsultaUtc");

                    b.ToTable("RegistrosConsultasAnalitica", "Analitica");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId", "EstaActivo");

                    b.HasIndex("PaisId", "Nombre")
                        .IsUnique();

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.TasaCambioRango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTasa")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoDesdeUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoHastaUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("PaisId", "SucursalId", "FechaTasa", "EstaActivo");

                    b.HasIndex("PaisId", "SucursalId", "FechaTasa", "MontoDesdeUsd", "MontoHastaUsd");

                    b.ToTable("TasasCambioRango", (string)null);
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.UsuarioAdministrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("UsuariosAdministradores", (string)null);
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.RegistroConsultaAnalitica", b =>
                {
                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.Pais", "Pais")
                        .WithMany("RegistrosConsultasAnalitica")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.Sucursal", "Sucursal")
                        .WithMany("RegistrosConsultasAnalitica")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.TasaCambioRango", "TasaCambioRango")
                        .WithMany("RegistrosConsultasAnalitica")
                        .HasForeignKey("TasaCambioRangoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");

                    b.Navigation("Sucursal");

                    b.Navigation("TasaCambioRango");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.Sucursal", b =>
                {
                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.Pais", "Pais")
                        .WithMany("Sucursales")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.TasaCambioRango", b =>
                {
                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.Pais", "Pais")
                        .WithMany("TasasCambioRango")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicaVallarta.Dominio.Entidades.Sucursal", "Sucursal")
                        .WithMany("TasasCambioRango")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.Pais", b =>
                {
                    b.Navigation("RegistrosConsultasAnalitica");

                    b.Navigation("Sucursales");

                    b.Navigation("TasasCambioRango");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.Sucursal", b =>
                {
                    b.Navigation("RegistrosConsultasAnalitica");

                    b.Navigation("TasasCambioRango");
                });

            modelBuilder.Entity("ElectronicaVallarta.Dominio.Entidades.TasaCambioRango", b =>
                {
                    b.Navigation("RegistrosConsultasAnalitica");
                });
#pragma warning restore 612, 618
        }
    }
}
